sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx
  
haxe:
  - "3.4.7"
  - development
  
matrix:
  allow_failures:
    - haxe: development
    
install:
  - npm i -g lix
  - lix download
  - lix run travix install

script:
  - lix run travix neko
  - lix run travix python
  - lix run travix node
  #- lix run travix flash -D flash-exit -D reporter=buddy.reporting.TraceReporter
  #- lix run travix java
  - lix run travix cpp
  - lix run travix php
